# =============================================================================
# modelPlots.R 
#
# Author       : Louis Chislett
#
# Purpose :
# Build model-performance, ROC/calibration, and SHAP contribution plots
# from CSV outputs generated by models.R.
# =============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(purrr)
  library(readr)
  library(ggplot2)
  library(lubridate)
  library(scales)
})

ascii_clean <- function(x){
  if (is.null(x)) return(x)
  if (is.factor(x)) x <- as.character(x)
  if (is.numeric(x) || is.integer(x)) x <- as.character(x)
  if (!is.character(x)) return(x)
  
  x <- enc2utf8(x)
  x <- gsub("\u00A0", " ", x, fixed = TRUE)
  x <- gsub("\u2013|\u2014|\u2212", "-", x)
  x <- gsub("\u2026", "...", x)
  x <- gsub("\u2018|\u2019", "'", x)
  x <- gsub("\u201C|\u201D", "\"", x)
  x <- gsub("\u0394", "Delta", x)
  x <- gsub("\u00B1", "+/-", x)
  
  iconv(x, from = "", to = "ASCII//TRANSLIT", sub = "")
}

ascii_vec <- function(x) if (is.null(x) || !length(x)) x else ascii_clean(x)
safe_lab  <- function(x) ascii_clean(x)

model_label <- function(x){
  dplyr::case_when(
    x == "COMBINED"     ~ "Overall",
    x == "COMBINED_POP" ~ "Overall (population weighted)",
    TRUE                ~ x
  ) %>% ascii_clean()
}

sanitize_weights <- function(w){
  w <- as.numeric(w)
  w[!is.finite(w) | is.na(w) | w <= 0] <- NA_real_
  w
}

.metric_inputs <- function(y, p, w){
  w <- sanitize_weights(w)
  ok <- is.finite(p) & !is.na(y) & is.finite(w) & !is.na(w) & w > 0
  list(
    y = as.integer(y[ok]),
    p = as.numeric(p[ok]),
    w = as.numeric(w[ok])
  )
}

w_mean <- function(x, w){
  ok <- is.finite(x) & is.finite(w) & !is.na(x) & !is.na(w) & w > 0
  if (!any(ok)) return(NA_real_)
  sum(w[ok] * x[ok]) / sum(w[ok])
}

.weighted_score_groups_desc <- function(y, p, w){
  z <- .metric_inputs(y, p, w)
  y <- z$y
  p <- z$p
  w <- z$w
  
  if (!length(y) || length(unique(y)) < 2) {
    return(list(ok = FALSE, groups = tibble(), w_pos_total = NA_real_, w_neg_total = NA_real_))
  }
  
  ord <- order(p, decreasing = TRUE)
  y <- y[ord]
  p <- p[ord]
  w <- w[ord]
  
  rr <- rle(p)
  ends <- cumsum(rr$lengths)
  starts <- c(1L, head(ends + 1L, -1L))
  
  grp_pos <- vapply(seq_along(starts), function(i){
    idx <- starts[i]:ends[i]
    sum(w[idx][y[idx] == 1L])
  }, numeric(1))
  
  grp_neg <- vapply(seq_along(starts), function(i){
    idx <- starts[i]:ends[i]
    sum(w[idx][y[idx] == 0L])
  }, numeric(1))
  
  groups <- tibble(score = rr$values, w_pos = grp_pos, w_neg = grp_neg)
  w_pos_total <- sum(groups$w_pos)
  w_neg_total <- sum(groups$w_neg)
  
  if (!is.finite(w_pos_total) || !is.finite(w_neg_total) || w_pos_total <= 0 || w_neg_total <= 0) {
    return(list(ok = FALSE, groups = tibble(), w_pos_total = w_pos_total, w_neg_total = w_neg_total))
  }
  
  list(ok = TRUE, groups = groups, w_pos_total = w_pos_total, w_neg_total = w_neg_total)
}

roc_auc_w <- function(y, p, w){
  obj <- .weighted_score_groups_desc(y, p, w)
  if (!isTRUE(obj$ok)) return(NA_real_)
  
  g <- obj$groups
  neg_after <- rev(c(0, head(cumsum(rev(g$w_neg)), -1L)))
  auc_num <- sum(g$w_pos * (neg_after + 0.5 * g$w_neg))
  auc_den <- obj$w_pos_total * obj$w_neg_total
  
  if (!is.finite(auc_den) || auc_den <= 0) return(NA_real_)
  auc_num / auc_den
}

roc_curve_w <- function(y, p, w){
  obj <- .weighted_score_groups_desc(y, p, w)
  if (!isTRUE(obj$ok)) return(tibble())
  
  g <- obj$groups
  tp <- cumsum(g$w_pos)
  fp <- cumsum(g$w_neg)
  
  curve <- tibble(
    threshold = g$score,
    tp = tp,
    fp = fp,
    tpr = tp / obj$w_pos_total,
    fpr = fp / obj$w_neg_total
  )
  
  bind_rows(
    tibble(threshold = Inf, tp = 0, fp = 0, tpr = 0, fpr = 0),
    curve
  )
}

calib_curve_w <- function(y, p, w, bins = 10){
  z <- .metric_inputs(y, p, w)
  y <- as.numeric(z$y)
  p <- z$p
  w <- z$w
  
  if (!length(y) || length(unique(y)) < 2) return(tibble())
  if (sum(w) <= 0) return(tibble())
  
  ord <- order(p)
  p <- p[ord]
  y <- y[ord]
  w <- w[ord]
  
  cw <- cumsum(w) / sum(w)
  bin_id <- ceiling(cw * bins)
  bin_id[bin_id < 1] <- 1L
  bin_id[bin_id > bins] <- bins
  
  tibble(p = p, y = y, w = w, bin = bin_id) %>%
    group_by(bin) %>%
    summarise(
      n = dplyr::n(),
      w_sum = sum(w),
      pred = w_mean(p, w),
      obs  = w_mean(y, w),
      .groups = "drop"
    ) %>%
    filter(is.finite(pred), is.finite(obs)) %>%
    arrange(pred)
}

.theme_base <- theme_minimal(base_size = 20) +
  theme(
    panel.grid.minor = element_blank(),
    axis.title = element_text(face = "bold", size = 20, colour = "black"),
    axis.text = element_text(size = 16, colour = "black"),
    legend.title = element_text(face = "bold", size = 18),
    legend.text = element_text(size = 16),
    plot.title = element_text(face = "bold", size = 22),
    plot.subtitle = element_text(size = 18)
  )

palette_models <- c(
  FE = "#d95f02",
  LTC = "#7570b3",
  YED = "#e7298a",
  COMBINED = "#1b9e77",
  COMBINED_POP = "#66a61e"
)

save_lineplot_ci <- function(df, x = "date", y, ymin, ymax, out_file, ylab){
  df_rib <- df %>% filter(is.finite(.data[[ymin]]), is.finite(.data[[ymax]]))
  
  p <- ggplot(df, aes(x = .data[[x]], y = .data[[y]], color = model)) +
    geom_ribbon(
      data = df_rib,
      mapping = aes(x = .data[[x]], ymin = .data[[ymin]], ymax = .data[[ymax]]),
      inherit.aes = FALSE,
      fill = "grey70", alpha = 0.35, color = NA
    ) +
    geom_line() +
    geom_point(size = 1) +
    scale_x_date(
      date_breaks = "1 year",
      date_labels = "%Y",
      expand = expansion(mult = c(0.03, 0.03))
    ) +
    scale_color_manual(values = palette_models, guide = "none") +
    labs(x = safe_lab("Month"), y = safe_lab(ylab)) +
    .theme_base +
    theme(
      legend.position = "none",
      plot.margin = margin(18, 26, 18, 18)
    ) +
    coord_cartesian(clip = "off")
  
  ggsave(out_file, p, width = 9.5, height = 5.2, dpi = 200, bg = "white", limitsize = FALSE)
}

roc_plot <- function(pred_df){
  if (!nrow(pred_df)) return(NULL)
  parts <- split(pred_df, pred_df$model)
  roc_rows <- list()
  labs <- list()
  
  for (mdl in names(parts)){
    dd <- parts[[mdl]]
    if (!nrow(dd) || length(unique(dd$y)) < 2) next
    
    rc <- roc_curve_w(dd$y, dd$p, dd$w)
    auc_val <- roc_auc_w(dd$y, dd$p, dd$w)
    
    if (!nrow(rc) || !is.finite(auc_val)) next
    
    roc_rows[[mdl]] <- rc %>% transmute(model = mdl, fpr = fpr, tpr = tpr)
    labs[[mdl]] <- ascii_clean(sprintf("%s (AUC %.3f)", model_label(mdl), auc_val))
  }
  
  rocs <- bind_rows(roc_rows)
  if (!nrow(rocs)) return(NULL)
  
  keep <- intersect(names(palette_models), unique(rocs$model))
  rocs$model <- factor(rocs$model, levels = keep)
  
  ggplot(rocs, aes(x = fpr, y = tpr, color = model)) +
    geom_path(linewidth = 1) +
    geom_abline(slope = 1, intercept = 0, linetype = 2) +
    coord_cartesian(
      xlim = c(0, 1),
      ylim = c(0, 1),
      expand = expansion(mult = c(0.06, 0.06)),
      clip = "off"
    ) +
    scale_x_continuous(labels = scales::percent) +
    scale_y_continuous(labels = scales::percent) +
    scale_color_manual(
      values = palette_models[keep],
      breaks = keep,
      labels = unname(unlist(labs[keep]))
    ) +
    labs(x = safe_lab("FPR"), y = safe_lab("TPR"), color = NULL) +
    .theme_base +
    theme(
      legend.position = "bottom",
      legend.box = "vertical",
      plot.margin = margin(22, 28, 22, 22)
    )
}

calib_plot <- function(pred_df, bins = 10){
  if (!nrow(pred_df)) return(NULL)
  parts <- split(pred_df, pred_df$model)
  
  curves <- imap(parts, function(dd, mdl){
    if (!nrow(dd) || length(unique(dd$y)) < 2) return(NULL)
    cdf <- calib_curve_w(dd$y, dd$p, dd$w, bins = bins)
    if (!nrow(cdf)) return(NULL)
    cdf$model <- mdl
    cdf
  }) %>% bind_rows()
  
  if (!nrow(curves)) return(NULL)
  
  keep <- intersect(names(palette_models), unique(curves$model))
  curves$model <- factor(curves$model, levels = keep)
  
  ggplot(curves, aes(x = pred, y = obs, color = model)) +
    geom_point(size = 2) +
    geom_line() +
    geom_abline(slope = 1, intercept = 0, linetype = 2) +
    coord_cartesian(
      xlim = c(0, 1),
      ylim = c(0, 1),
      expand = expansion(mult = c(0.06, 0.06)),
      clip = "off"
    ) +
    scale_color_manual(values = palette_models[keep], breaks = keep, labels = model_label(keep)) +
    labs(
      x = safe_lab("Predicted risk"),
      y = safe_lab("Observed risk"),
      color = safe_lab("Model")
    ) +
    .theme_base +
    theme(
      legend.position = "bottom",
      legend.box = "vertical",
      plot.margin = margin(18, 26, 18, 18)
    )
}

save_shap_lineplot <- function(df, out_file, y_col, ylab, ci_low_col = NULL, ci_high_col = NULL){
  if (!y_col %in% names(df)) {
    warning(sprintf("Skipping SHAP plot '%s': column '%s' not found.", basename(out_file), y_col), call. = FALSE)
    return(invisible(NULL))
  }
  df <- df %>% arrange(date)
  p <- ggplot(df, aes(x = date, y = .data[[y_col]], group = 1))
  
  rib_ok <- FALSE
  if (!is.null(ci_low_col) && !is.null(ci_high_col) &&
      ci_low_col %in% names(df) && ci_high_col %in% names(df)) {
    rib_ok <- any(is.finite(df[[ci_low_col]]) & is.finite(df[[ci_high_col]]), na.rm = TRUE)
    
    if (rib_ok) {
      width_ok <- any(abs(df[[ci_high_col]] - df[[ci_low_col]]) > 0, na.rm = TRUE)
      if (!width_ok) {
        warning(sprintf("Zero-width SHAP CI ribbon for '%s' in '%s'.", y_col, basename(out_file)), call. = FALSE)
      }
      
      p <- p +
        geom_ribbon(
          aes(ymin = .data[[ci_low_col]], ymax = .data[[ci_high_col]]),
          inherit.aes = TRUE,
          fill = "grey70",
          alpha = 0.35,
          colour = NA
        )
    } else {
      warning(sprintf("No finite SHAP CI values for '%s' in '%s'.", y_col, basename(out_file)), call. = FALSE)
    }
  }
  
  p <- p +
    geom_line(linewidth = 0.6, colour = "black") +
    geom_point(size = 0.9, colour = "black") +
    scale_x_date(
      date_breaks = "1 year",
      date_labels = "%Y",
      expand = expansion(mult = c(0.03, 0.03))
    ) +
    labs(
      x = safe_lab("Month"),
      y = safe_lab(ylab)
    ) +
    .theme_base +
    theme(plot.margin = margin(18, 26, 18, 18)) +
    coord_cartesian(clip = "off")
  
  ggsave(out_file, p, width = 9.5, height = 5.2, dpi = 200, bg = "white", limitsize = FALSE)
}

read_csv_if_exists <- function(path, col_types = cols()){
  if (!file.exists(path)) return(NULL)
  readr::read_csv(path, col_types = col_types, show_col_types = FALSE)
}

save_metric_plots <- function(results_dir, plot_dir, train_key = "2012-01"){
  ref_dir <- file.path(results_dir, "reference weighted")
  pop_dir <- file.path(results_dir, "population weighted")
  dir.create(ref_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(pop_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(plot_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(plot_dir, "reference weighted"), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(plot_dir, "population weighted"), recursive = TRUE, showWarnings = FALSE)
  
  perf_ref <- read_csv_if_exists(file.path(ref_dir, "performance_reference_weighted.csv"))
  perf_pop <- read_csv_if_exists(file.path(pop_dir, "performance_population_weighted.csv"))
  
  if (!is.null(perf_ref) && nrow(perf_ref)) {
    perf_ref <- perf_ref %>% mutate(date = as.Date(date), model = ascii_vec(model))
    for (mdl in c("FE", "LTC", "YED", "COMBINED")) {
      dfm <- perf_ref %>% filter(model == mdl)
      if (!nrow(dfm)) next
      
      save_lineplot_ci(
        dfm, y = "auc", ymin = "auc_ci_low", ymax = "auc_ci_high",
        out_file = file.path(plot_dir, "reference weighted", sprintf("auc_over_time_%s__%s.png", mdl, train_key)),
        ylab = "AUC"
      )
      save_lineplot_ci(
        dfm, y = "pr_auc", ymin = "pr_auc_ci_low", ymax = "pr_auc_ci_high",
        out_file = file.path(plot_dir, "reference weighted", sprintf("pr_auc_over_time_%s__%s.png", mdl, train_key)),
        ylab = "PR AUC"
      )
      save_lineplot_ci(
        dfm, y = "accuracy", ymin = "accuracy_ci_low", ymax = "accuracy_ci_high",
        out_file = file.path(plot_dir, "reference weighted", sprintf("accuracy_over_time_%s__%s.png", mdl, train_key)),
        ylab = "Accuracy"
      )
      save_lineplot_ci(
        dfm, y = "precision", ymin = "precision_ci_low", ymax = "precision_ci_high",
        out_file = file.path(plot_dir, "reference weighted", sprintf("precision_over_time_%s__%s.png", mdl, train_key)),
        ylab = "Precision"
      )
      save_lineplot_ci(
        dfm, y = "recall", ymin = "recall_ci_low", ymax = "recall_ci_high",
        out_file = file.path(plot_dir, "reference weighted", sprintf("recall_over_time_%s__%s.png", mdl, train_key)),
        ylab = "Recall"
      )
      save_lineplot_ci(
        dfm, y = "log_loss", ymin = "log_loss_ci_low", ymax = "log_loss_ci_high",
        out_file = file.path(plot_dir, "reference weighted", sprintf("logloss_over_time_%s__%s.png", mdl, train_key)),
        ylab = "Log loss"
      )
    }
  }
  
  if (!is.null(perf_pop) && nrow(perf_pop)) {
    perf_pop <- perf_pop %>% mutate(date = as.Date(date), model = ascii_vec(model))
    for (mdl in c("COMBINED_POP")) {
      dfm <- perf_pop %>% filter(model == mdl)
      if (!nrow(dfm)) next
      
      save_lineplot_ci(
        dfm, y = "auc", ymin = "auc_ci_low", ymax = "auc_ci_high",
        out_file = file.path(plot_dir, "population weighted", sprintf("auc_over_time_%s__%s.png", mdl, train_key)),
        ylab = "AUC"
      )
      save_lineplot_ci(
        dfm, y = "pr_auc", ymin = "pr_auc_ci_low", ymax = "pr_auc_ci_high",
        out_file = file.path(plot_dir, "population weighted", sprintf("pr_auc_over_time_%s__%s.png", mdl, train_key)),
        ylab = "PR AUC"
      )
      save_lineplot_ci(
        dfm, y = "accuracy", ymin = "accuracy_ci_low", ymax = "accuracy_ci_high",
        out_file = file.path(plot_dir, "population weighted", sprintf("accuracy_over_time_%s__%s.png", mdl, train_key)),
        ylab = "Accuracy"
      )
      save_lineplot_ci(
        dfm, y = "precision", ymin = "precision_ci_low", ymax = "precision_ci_high",
        out_file = file.path(plot_dir, "population weighted", sprintf("precision_over_time_%s__%s.png", mdl, train_key)),
        ylab = "Precision"
      )
      save_lineplot_ci(
        dfm, y = "recall", ymin = "recall_ci_low", ymax = "recall_ci_high",
        out_file = file.path(plot_dir, "population weighted", sprintf("recall_over_time_%s__%s.png", mdl, train_key)),
        ylab = "Recall"
      )
      save_lineplot_ci(
        dfm, y = "log_loss", ymin = "log_loss_ci_low", ymax = "log_loss_ci_high",
        out_file = file.path(plot_dir, "population weighted", sprintf("logloss_over_time_%s__%s.png", mdl, train_key)),
        ylab = "Log loss"
      )
    }
  }
  
  preds_ref <- read_csv_if_exists(file.path(ref_dir, "selected_predictions_reference_weighted.csv"))
  if (!is.null(preds_ref) && nrow(preds_ref)) {
    for (ym in unique(preds_ref$year_month)) {
      preds <- preds_ref %>% filter(year_month == ym)
      p1 <- roc_plot(preds)
      if (!is.null(p1)) {
        ggsave(
          file.path(plot_dir, "reference weighted", sprintf("ROC_%s__FE_LTC_YED_COMBINED.png", ym)),
          p1, width = 8.8, height = 7.2, dpi = 200, bg = "white", limitsize = FALSE
        )
      }
      p2 <- calib_plot(preds, bins = 10)
      if (!is.null(p2)) {
        ggsave(
          file.path(plot_dir, "reference weighted", sprintf("Calibration_%s__FE_LTC_YED_COMBINED.png", ym)),
          p2, width = 8.6, height = 6.8, dpi = 200, bg = "white", limitsize = FALSE
        )
      }
    }
  }
  
  preds_pop <- read_csv_if_exists(file.path(pop_dir, "selected_predictions_population_weighted.csv"))
  if (!is.null(preds_pop) && nrow(preds_pop)) {
    for (ym in unique(preds_pop$year_month)) {
      preds <- preds_pop %>% filter(year_month == ym)
      p1 <- roc_plot(preds)
      if (!is.null(p1)) {
        ggsave(
          file.path(plot_dir, "population weighted", sprintf("ROC_%s__COMBINED_POP.png", ym)),
          p1, width = 8.8, height = 7.2, dpi = 200, bg = "white", limitsize = FALSE
        )
      }
      p2 <- calib_plot(preds, bins = 10)
      if (!is.null(p2)) {
        ggsave(
          file.path(plot_dir, "population weighted", sprintf("Calibration_%s__COMBINED_POP.png", ym)),
          p2, width = 8.6, height = 6.8, dpi = 200, bg = "white", limitsize = FALSE
        )
      }
    }
  }
}

normalise_shap_term_column <- function(df){
  if (is.null(df) || !nrow(df)) return(df)
  
  if (!"variable" %in% names(df) && "term" %in% names(df)) {
    df <- df %>% rename(variable = term)
  }
  
  # New shared-bootstrap models.R names -> old plotting names
  if (!"diff_phi" %in% names(df) && "diff_post_minus_pre" %in% names(df)) {
    df <- df %>% rename(diff_phi = diff_post_minus_pre)
  }
  
  if (!"diff_phi_ci_low" %in% names(df) && "diff_ci_low" %in% names(df)) {
    df <- df %>% rename(diff_phi_ci_low = diff_ci_low)
  }
  
  if (!"diff_phi_ci_high" %in% names(df) && "diff_ci_high" %in% names(df)) {
    df <- df %>% rename(diff_phi_ci_high = diff_ci_high)
  }
  
  if (!"mean_phi_pre" %in% names(df) && "mean_pre" %in% names(df)) {
    df <- df %>% rename(mean_phi_pre = mean_pre)
  }
  
  if (!"mean_phi_post" %in% names(df) && "mean_post" %in% names(df)) {
    df <- df %>% rename(mean_phi_post = mean_post)
  }
  
  if (!"comparison" %in% names(df) &&
      all(c("post_month", "pre_month") %in% names(df))) {
    df <- df %>%
      mutate(comparison = paste0(post_month, " - ", pre_month))
  }
  
  df
}

save_shap_difference_plot <- function(df, out_file, mdl, conf = 0.95, comparison_label = NULL){
  if (is.null(df) || !nrow(df)) return(invisible(NULL))
  df <- normalise_shap_term_column(df)
  if (!"variable" %in% names(df)) {
    warning(sprintf("Skipping SHAP difference plot for %s: neither 'variable' nor 'term' column found.", mdl), call. = FALSE)
    return(invisible(NULL))
  }
  
  if (is.null(comparison_label)) {
    comparison_label <- unique(df$comparison)
    comparison_label <- comparison_label[!is.na(comparison_label)][1]
    if (!length(comparison_label) || is.na(comparison_label)) comparison_label <- "Difference in mean contribution"
  }
  
  if ("variable" %in% names(df) && any(tolower(df$variable) == "model", na.rm = TRUE)) {
    warning(sprintf("Dropping spurious 'model' term from SHAP difference plot for %s.", mdl), call. = FALSE)
  }
  
  dd <- df %>%
    filter(!is.na(variable), tolower(variable) != "model") %>%
    mutate(variable = ascii_clean(variable)) %>%
    arrange(diff_phi) %>%
    mutate(variable = factor(variable, levels = variable))
  
  if (!nrow(dd)) return(invisible(NULL))
  
  bad_ci <- !(is.finite(dd$diff_phi_ci_low) & is.finite(dd$diff_phi_ci_high))
  if (any(bad_ci, na.rm = TRUE)) {
    warning(sprintf("Some SHAP difference CI values are missing for %s; plotting point estimates where available.", mdl), call. = FALSE)
  }
  
  p <- ggplot(dd, aes(x = variable, y = diff_phi)) +
    geom_hline(yintercept = 0, linetype = 2, colour = "grey50") +
    geom_linerange(aes(ymin = diff_phi_ci_low, ymax = diff_phi_ci_high), linewidth = 0.5, na.rm = TRUE) +
    geom_point(size = 1.8, na.rm = TRUE) +
    labs(
      x = safe_lab("Model term"),
      y = safe_lab("Change in contribution")
    ) +
    .theme_base +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 16, colour = "black"),
      axis.title.x = element_text(face = "bold", size = 20, colour = "black"),
      axis.title.y = element_text(face = "bold", size = 20, colour = "black"),
      plot.margin = margin(80, 26, 18, 18)
    ) +
    coord_cartesian(clip = "off")
  
  ggsave(out_file, p, width = 12.5, height = 6.8, dpi = 200, bg = "white", limitsize = FALSE)
  invisible(NULL)
}

save_shap_difference_plots_from_csv <- function(results_dir, plot_dir, conf = 0.95,
                                                pre_month = "2020-03", post_month = "2021-03"){
  shap_dir <- file.path(results_dir, "shap")
  out_shap_dir <- file.path(plot_dir, "shap")
  dir.create(out_shap_dir, recursive = TRUE, showWarnings = FALSE)
  
  for (mdl in c("FE", "LTC", "YED")) {
    in_file <- file.path(
      shap_dir, mdl,
      sprintf("shap_diff_summary_%s_%s_minus_%s.csv", mdl, gsub("-", "_", post_month), gsub("-", "_", pre_month))
    )
    ss <- read_csv_if_exists(in_file)
    if (is.null(ss) || !nrow(ss)) next
    
    mdl_dir <- file.path(out_shap_dir, mdl)
    dir.create(mdl_dir, recursive = TRUE, showWarnings = FALSE)
    
    comparison_label <- unique(ss$comparison)
    comparison_label <- comparison_label[!is.na(comparison_label)][1]
    
    save_shap_difference_plot(
      ss,
      out_file = file.path(mdl_dir, sprintf("shap_diff_mean_phi_%s_%s_minus_%s.png", mdl, gsub("-", "_", post_month), gsub("-", "_", pre_month))),
      mdl = mdl,
      conf = conf,
      comparison_label = comparison_label
    )
  }
}

save_shap_plots_from_csv <- function(results_dir, plot_dir, conf = 0.95){
  shap_dir <- file.path(results_dir, "shap")
  out_shap_dir <- file.path(plot_dir, "shap")
  dir.create(out_shap_dir, recursive = TRUE, showWarnings = FALSE)
  
  conf_pct <- formatC(100 * conf, format = "fg", digits = 3)
  
  for (mdl in c("FE", "LTC", "YED")) {
    in_file <- file.path(shap_dir, mdl, sprintf("shap_summary_%s.csv", mdl))
    ss <- read_csv_if_exists(in_file)
    if (is.null(ss) || !nrow(ss)) next
    ss <- normalise_shap_term_column(ss)
    if (!"variable" %in% names(ss)) {
      warning(sprintf("Skipping SHAP summary plots for %s: neither 'variable' nor 'term' column found.", mdl), call. = FALSE)
      next
    }
    
    ss <- ss %>% mutate(date = as.Date(date))
    mdl_dir <- file.path(out_shap_dir, mdl)
    dir.create(mdl_dir, recursive = TRUE, showWarnings = FALSE)
    
    vars_to_plot <- unique(ss$variable)
    if (any(tolower(vars_to_plot) == "model", na.rm = TRUE)) {
      warning(sprintf("Dropping spurious 'model' term from SHAP summary plots for %s.", mdl), call. = FALSE)
      vars_to_plot <- vars_to_plot[tolower(vars_to_plot) != "model"]
    }
    
    for (v in vars_to_plot) {
      dd <- ss %>% filter(variable == v) %>% arrange(date)
      safe_v <- gsub("[^A-Za-z0-9_]+", "_", ascii_clean(v))
      
      save_shap_lineplot(
        dd,
        out_file = file.path(mdl_dir, sprintf("shap_mean_phi_%s_%s.png", mdl, safe_v)),
        y_col = "mean_phi",
        ylab = "Mean log-odds contribution",
        ci_low_col = "mean_phi_ci_low",
        ci_high_col = "mean_phi_ci_high"
      )
    }
  }
}

run_model_plots <- function(results_dir = "results",
                            plot_dir = "model plots",
                            train_key = "2012-01",
                            shap_ci_conf = 0.95,
                            pre_covid_key = "2020-03",
                            post_covid_key = "2021-03") {
  dir.create(plot_dir, recursive = TRUE, showWarnings = FALSE)
  save_metric_plots(results_dir = results_dir, plot_dir = plot_dir, train_key = train_key)
  save_shap_plots_from_csv(results_dir = results_dir, plot_dir = plot_dir, conf = shap_ci_conf)
  save_shap_difference_plots_from_csv(
    results_dir = results_dir,
    plot_dir = plot_dir,
    conf = shap_ci_conf,
    pre_month = pre_covid_key,
    post_month = post_covid_key
  )
  invisible(list(results_dir = results_dir, plot_dir = plot_dir))
}